name: neuronbridge-python
channels:
  - defaults
  - conda-forge
  - flyem-forge
dependencies:
  - python=3.8
  - jupyter
  - pillow
  - requests
  - pydantic=1.10.2
  - python-devtools
  - numpy
  - pandas
  - twine
  - python-rapidjson
  - neuprint-python
  - pymongo=3.12.0
  - pip-tools
  - pipreqs
  - pytest
  - pip
  - pip:
    - ray[default]
