name: neuronbridge-python
channels:
  - flyem-forge
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.8
  - jupyter
  - pillow
  - requests
  - pydantic
  - python-devtools
  - numpy
  - pandas
  - neuprint-python
  - pip-tools
  - pipreqs
  - twine
